version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # AMQP (service-to-service)
      - "15672:15672"   # Web UI (for you)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  booking-service:
    build: ./BookingService
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq

  payment-service:
    build: ./PaymentService
    ports:
      - "5002:80"
    depends_on:
      - rabbitmq
