// <auto-generated />
using System;
using DBModels.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DBModels.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211104752_AddSeatLocking")]
    partial class AddSeatLocking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DBModels.Models.Billingsummary", b =>
                {
                    b.Property<int>("Billingsummaryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("billingsummaryid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Billingsummaryid"));

                    b.Property<decimal?>("Baseamount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("baseamount");

                    b.Property<int?>("Bookingid")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("discount");

                    b.Property<decimal?>("Gst")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("gst");

                    b.Property<decimal?>("Servicefee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("servicefee");

                    b.Property<decimal?>("Totalamount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("totalamount");

                    b.HasKey("Billingsummaryid")
                        .HasName("billingsummaries_pkey");

                    b.HasIndex("Bookingid");

                    b.ToTable("billingsummaries", (string)null);
                });

            modelBuilder.Entity("DBModels.Models.Booking", b =>
                {
                    b.Property<int>("Bookingid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Bookingid"));

                    b.Property<decimal?>("Baseprice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("baseprice");

                    b.Property<DateTime>("Bookingtime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("bookingtime");

                    b.Property<DateTime?>("Cancelledat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cancelledat");

                    b.Property<bool?>("Emailsent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("emailsent");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<bool?>("Isrefunded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isrefunded");

                    b.Property<int?>("Movieid")
                        .HasColumnType("integer")
                        .HasColumnName("movieid");

                    b.Property<decimal?>("Refundamount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("refundamount");

                    b.Property<int?>("Seatid")
                        .HasColumnType("integer")
                        .HasColumnName("seatid");

                    b.Property<string>("Seatnumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("seatnumber");

                    b.Property<int?>("Showinstanceid")
                        .HasColumnType("integer")
                        .HasColumnName("showinstanceid");

                    b.Property<DateTime>("Showtime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("showtime");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int?>("Theaterid")
                        .HasColumnType("integer")
                        .HasColumnName("theaterid");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<int?>("VenueId")
                        .HasColumnType("integer");

                    b.HasKey("Bookingid")
                        .HasName("bookings_pkey");

                    b.HasIndex("EventId");

                    b.HasIndex("Movieid");

                    b.HasIndex("Seatid");

                    b.HasIndex("Showinstanceid");

                    b.HasIndex("Theaterid");

                    b.HasIndex("Userid");

                    b.HasIndex("VenueId");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("DBModels.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DBModels.Models.Movie", b =>
                {
                    b.Property<int>("Movieid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("movieid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Movieid"));

                    b.Property<string>("Duration")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("duration");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("genre");

                    b.Property<DateOnly?>("Releasedate")
                        .HasColumnType("date")
                        .HasColumnName("releasedate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Movieid")
                        .HasName("movies_pkey");

                    b.ToTable("movies", (string)null);
                });

            modelBuilder.Entity("DBModels.Models.Movietheater", b =>
                {
                    b.Property<int>("Movieid")
                        .HasColumnType("integer")
                        .HasColumnName("movieid");

                    b.Property<int>("Theaterid")
                        .HasColumnType("integer")
                        .HasColumnName("theaterid");

                    b.HasKey("Movieid", "Theaterid")
                        .HasName("movietheater_pkey");

                    b.HasIndex("Theaterid");

                    b.ToTable("movietheaters", (string)null);
                });

            modelBuilder.Entity("DBModels.Models.Payment", b =>
                {
                    b.Property<int>("Paymentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("paymentid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Paymentid"));

                    b.Property<decimal>("Amountpaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amountpaid");

                    b.Property<int?>("Bookingid")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<DateTime>("Paymentdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paymentdate");

                    b.Property<string>("Paymentmethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("paymentmethod");

                    b.Property<DateTime?>("Refunddate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("refunddate");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Success'::character varying");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.HasKey("Paymentid")
                        .HasName("payments_pkey");

                    b.HasIndex("Bookingid");

                    b.HasIndex("Userid");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("DBModels.Models.Seat", b =>
                {
                    b.Property<int>("Seatid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("seatid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Seatid"));

                    b.Property<decimal>("Baseprice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("baseprice");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("row");

                    b.Property<int>("Theaterid")
                        .HasColumnType("integer")
                        .HasColumnName("theaterid");

                    b.HasKey("Seatid")
                        .HasName("seats_pkey");

                    b.HasIndex("Theaterid");

                    b.ToTable("seats", (string)null);
                });

            modelBuilder.Entity("DBModels.Models.Showinstance", b =>
                {
                    b.Property<int>("Showinstanceid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("showinstanceid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Showinstanceid"));

                    b.Property<int?>("Availableseats")
                        .HasColumnType("integer")
                        .HasColumnName("availableseats");

                    b.Property<DateOnly?>("Showdate")
                        .HasColumnType("date")
                        .HasColumnName("showdate");

                    b.Property<int?>("Showtemplateid")
                        .HasColumnType("integer")
                        .HasColumnName("showtemplateid");

                    b.Property<TimeOnly?>("Showtime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("showtime");

                    b.HasKey("Showinstanceid")
                        .HasName("showinstances_pkey");

                    b.HasIndex("Showtemplateid");

                    b.ToTable("showinstances", (string)null);
                });

            modelBuilder.Entity("DBModels.Models.Showseatstatus", b =>
                {
                    b.Property<int>("Showseatstatusid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("showseatstatusid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Showseatstatusid"));

                    b.Property<bool>("Isbooked")
                        .HasColumnType("boolean")
                        .HasColumnName("isbooked");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text");

                    b.Property<int>("Seatid")
                        .HasColumnType("integer")
                        .HasColumnName("seatid");

                    b.Property<int>("Showinstanceid")
                        .HasColumnType("integer")
                        .HasColumnName("showinstanceid");

                    b.HasKey("Showseatstatusid")
                        .HasName("showseatstatuses_pkey");

                    b.HasIndex("Seatid");

                    b.HasIndex("Showinstanceid");

                    b.ToTable("showseatstatuses", (string)null);
                });

            modelBuilder.Entity("DBModels.Models.Showtemplate", b =>
                {
                    b.Property<int>("Showtemplateid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("showtemplateid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Showtemplateid"));

                    b.Property<decimal?>("Baseprice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("baseprice");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Format")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("format");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("language");

                    b.Property<int?>("Movieid")
                        .HasColumnType("integer")
                        .HasColumnName("movieid");

                    b.Property<int?>("Theaterid")
                        .HasColumnType("integer")
                        .HasColumnName("theaterid");

                    b.Property<int?>("VenueId")
                        .HasColumnType("integer");

                    b.HasKey("Showtemplateid")
                        .HasName("showtemplates_pkey");

                    b.HasIndex("EventId");

                    b.HasIndex("Movieid");

                    b.HasIndex("Theaterid");

                    b.HasIndex("VenueId");

                    b.ToTable("showtemplates", (string)null);
                });

            modelBuilder.Entity("DBModels.Models.Theater", b =>
                {
                    b.Property<int>("Theaterid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("theaterid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Theaterid"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Theaterid")
                        .HasName("theaters_pkey");

                    b.ToTable("theaters", (string)null);
                });

            modelBuilder.Entity("DBModels.Models.User", b =>
                {
                    b.Property<int>("Userid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Userid"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<byte[]>("Passwordsalt")
                        .HasColumnType("bytea")
                        .HasColumnName("passwordsalt");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Userid")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DBModels.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VenueId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("integer");

                    b.HasKey("VenueId");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("DBModels.Models.VenueSection", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SectionId"));

                    b.Property<decimal>("BasePriceMultiplier")
                        .HasColumnType("numeric");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.Property<int>("SeatsPerRow")
                        .HasColumnType("integer");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.HasKey("SectionId");

                    b.HasIndex("VenueId");

                    b.ToTable("VenueSections");
                });

            modelBuilder.Entity("MovieTheater", b =>
                {
                    b.Property<int>("MoviesMovieid")
                        .HasColumnType("integer");

                    b.Property<int>("TheatersTheaterid")
                        .HasColumnType("integer");

                    b.HasKey("MoviesMovieid", "TheatersTheaterid");

                    b.HasIndex("TheatersTheaterid");

                    b.ToTable("MovieTheater");
                });

            modelBuilder.Entity("DBModels.Models.Billingsummary", b =>
                {
                    b.HasOne("DBModels.Models.Booking", "Booking")
                        .WithMany("Billingsummaries")
                        .HasForeignKey("Bookingid")
                        .HasConstraintName("billingsummaries_bookingid_fkey");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("DBModels.Models.Booking", b =>
                {
                    b.HasOne("DBModels.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("DBModels.Models.Movie", "Movie")
                        .WithMany("Bookings")
                        .HasForeignKey("Movieid")
                        .HasConstraintName("bookings_movieid_fkey");

                    b.HasOne("DBModels.Models.Seat", "Seat")
                        .WithMany("Bookings")
                        .HasForeignKey("Seatid")
                        .HasConstraintName("bookings_seatid_fkey");

                    b.HasOne("DBModels.Models.Showinstance", "Showinstance")
                        .WithMany("Bookings")
                        .HasForeignKey("Showinstanceid")
                        .HasConstraintName("bookings_showinstanceid_fkey");

                    b.HasOne("DBModels.Models.Theater", "Theater")
                        .WithMany("Bookings")
                        .HasForeignKey("Theaterid")
                        .HasConstraintName("bookings_theaterid_fkey");

                    b.HasOne("DBModels.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("Userid")
                        .IsRequired()
                        .HasConstraintName("bookings_userid_fkey");

                    b.HasOne("DBModels.Models.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId");

                    b.Navigation("Event");

                    b.Navigation("Movie");

                    b.Navigation("Seat");

                    b.Navigation("Showinstance");

                    b.Navigation("Theater");

                    b.Navigation("User");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("DBModels.Models.Movietheater", b =>
                {
                    b.HasOne("DBModels.Models.Movie", "Movie")
                        .WithMany("Movietheater")
                        .HasForeignKey("Movieid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("movietheaters_movieid_fkey");

                    b.HasOne("DBModels.Models.Theater", "Theater")
                        .WithMany("Movietheater")
                        .HasForeignKey("Theaterid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("movietheaters_theaterid_fkey");

                    b.Navigation("Movie");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("DBModels.Models.Payment", b =>
                {
                    b.HasOne("DBModels.Models.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("Bookingid")
                        .HasConstraintName("payments_bookingid_fkey");

                    b.HasOne("DBModels.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("Userid")
                        .IsRequired()
                        .HasConstraintName("payments_userid_fkey");

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DBModels.Models.Seat", b =>
                {
                    b.HasOne("DBModels.Models.Theater", "Theater")
                        .WithMany("Seats")
                        .HasForeignKey("Theaterid")
                        .IsRequired()
                        .HasConstraintName("seats_theaterid_fkey");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("DBModels.Models.Showinstance", b =>
                {
                    b.HasOne("DBModels.Models.Showtemplate", "Showtemplate")
                        .WithMany("Showinstances")
                        .HasForeignKey("Showtemplateid")
                        .HasConstraintName("showinstances_showtemplateid_fkey");

                    b.Navigation("Showtemplate");
                });

            modelBuilder.Entity("DBModels.Models.Showseatstatus", b =>
                {
                    b.HasOne("DBModels.Models.Seat", "Seat")
                        .WithMany("Showseatstatuses")
                        .HasForeignKey("Seatid")
                        .IsRequired()
                        .HasConstraintName("showseatstatuses_seatid_fkey");

                    b.HasOne("DBModels.Models.Showinstance", "Showinstance")
                        .WithMany("Showseatstatuses")
                        .HasForeignKey("Showinstanceid")
                        .IsRequired()
                        .HasConstraintName("showseatstatuses_showinstanceid_fkey");

                    b.Navigation("Seat");

                    b.Navigation("Showinstance");
                });

            modelBuilder.Entity("DBModels.Models.Showtemplate", b =>
                {
                    b.HasOne("DBModels.Models.Event", "Event")
                        .WithMany("Showtemplates")
                        .HasForeignKey("EventId");

                    b.HasOne("DBModels.Models.Movie", "Movie")
                        .WithMany("Showtemplates")
                        .HasForeignKey("Movieid")
                        .HasConstraintName("showtemplates_movieid_fkey");

                    b.HasOne("DBModels.Models.Theater", "Theater")
                        .WithMany("Showtemplates")
                        .HasForeignKey("Theaterid")
                        .HasConstraintName("showtemplates_theaterid_fkey");

                    b.HasOne("DBModels.Models.Venue", "NewVenue")
                        .WithMany()
                        .HasForeignKey("VenueId");

                    b.Navigation("Event");

                    b.Navigation("Movie");

                    b.Navigation("NewVenue");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("DBModels.Models.VenueSection", b =>
                {
                    b.HasOne("DBModels.Models.Venue", "Venue")
                        .WithMany("Sections")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("MovieTheater", b =>
                {
                    b.HasOne("DBModels.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesMovieid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBModels.Models.Theater", null)
                        .WithMany()
                        .HasForeignKey("TheatersTheaterid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DBModels.Models.Booking", b =>
                {
                    b.Navigation("Billingsummaries");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DBModels.Models.Event", b =>
                {
                    b.Navigation("Showtemplates");
                });

            modelBuilder.Entity("DBModels.Models.Movie", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Movietheater");

                    b.Navigation("Showtemplates");
                });

            modelBuilder.Entity("DBModels.Models.Seat", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Showseatstatuses");
                });

            modelBuilder.Entity("DBModels.Models.Showinstance", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Showseatstatuses");
                });

            modelBuilder.Entity("DBModels.Models.Showtemplate", b =>
                {
                    b.Navigation("Showinstances");
                });

            modelBuilder.Entity("DBModels.Models.Theater", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Movietheater");

                    b.Navigation("Seats");

                    b.Navigation("Showtemplates");
                });

            modelBuilder.Entity("DBModels.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DBModels.Models.Venue", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
